services:
  app:
    image: algolia:latest
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 5s
      timeout: 3s
      retries: 3
    restart: always
  nginx:
    depends_on:
      - app
    image: nginx:latest
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./htpasswd:/etc/nginx/conf.d/htpasswd